name: Update RSS Feeds

on:
  schedule:
    - cron: '*/15 * * * *'  # 15分おきに実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # requests, beautifulsoup4, feedparser, lxmlをインストール

    - name: Run the RSS filter script
      run: |
        python main.py

    - name: Check for changes and commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # ファイルに変更があればコミットする
        if [[ $(git status --porcelain) ]]; then
          git add output*.xml  # 複数のoutputファイルを対象に追加
          git commit -m "Update filtered RSS feeds"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        else
          echo "No changes to commit"
        fi
